In [2]:
import pandas as pd

In [3]:
from scipy import stats

In [4]:
from scipy.stats import f_oneway

In [5]:
import numpy as np

In [6]:
df = pd.read_csv("./df_after_corr_drop2.csv")

In [6]:
df

,hospital_death,age,bmi,gender,icu_admit_source,icu_stay_type,icu_type,pre_icu_los_days,apache_2_diagnosis,ventilated_apache,...,d1_wbc_min,apache_4a_icu_death_prob,aids,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem
0,0,68,22.730000,1,3,1,8,0.541667,113,0,...,14.10,0.05,0,1,0,0,0,0,0,3
1,0,77,27.420000,2,3,1,1,0.927778,108,1,...,12.70,0.29,0,1,0,0,0,0,0,4
2,0,25,31.950000,2,1,1,1,0.000694,122,0,...,10.10,0.00,0,0,0,0,0,0,0,6
3,0,81,22.640000,2,2,1,8,0.000694,203,1,...,8.00,0.03,0,0,0,0,0,0,0,1
4,0,19,27.654655,1,1,1,1,0.073611,119,0,...,10.10,0.02,0,0,0,0,0,0,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,0,75,23.060250,1,3,1,6,0.298611,113,1,...,5.68,0.05,0,1,0,0,0,0,1,3
91709,0,56,47.179671,2,3,1,1,0.120139,113,0,...,4.22,0.02,0,0,0,0,0,0,0,3
91710,0,48,27.236914,1,1,1,1,0.046528,123,0,...,17.55,0.02,0,1,0,0,0,0,0,6
91711,0,65,23.297481,2,1,1,1,0.081944,108,0,...,10.10,0.02,0,0,0,0,0,0,0,4
91712,0,82,22.031250,2,2,1,1,0.018056,304,1,...,24.40,0.08,0,0,0,0,0,0,0,5

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91713 entries, 0 to 91712
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   hospital_death               91713 non-null  int64
 1   age                          91713 non-null  int64
 2   bmi                          91713 non-null  float64
 3   gender                       91713 non-null  int64
 4   icu_admit_source             91713 non-null  int64
 5   icu_stay_type                91713 non-null  int64
 6   icu_type                     91713 non-null  int64
 7   pre_icu_los_days             91713 non-null  float64
 8   apache_2_diagnosis           91713 non-null  int64
 9   ventilated_apache            91713 non-null  int64
 10  d1_temp_max                  91713 non-null  float64
 11  d1_temp_min                  91713 non-null  float64
 12  h1_resprate_max              91713 non-null  int64
 13  h1_resprate_min              91713 non-null  float64
 14  h1_spo2_max                  91713 non-null  float64
 15  h1_spo2_min                  91713 non-null  int64
 16  d1_calcium_min               91713 non-null  float64
 17  d1_hco3_max                  91713 non-null  float64
 18  d1_hematocrit_min            91713 non-null  float64
 19  d1_platelets_max             91713 non-null  int64
 20  d1_potassium_max             91713 non-null  float64
 21  d1_sodium_min                91713 non-null  float64
 22  d1_wbc_min                   91713 non-null  float64
 23  apache_4a_icu_death_prob     91713 non-null  float64
 24  aids                         91713 non-null  int64
 25  diabetes_mellitus            91713 non-null  int64
 26  hepatic_failure              91713 non-null  int64
 27  immunosuppression            91713 non-null  int64
 28  leukemia                     91713 non-null  int64
 29  lymphoma                     91713 non-null  int64
 30  solid_tumor_with_metastasis  91713 non-null  int64
 31  apache_3j_bodysystem         91713 non-null  int64
dtypes: float64(13), int64(19)
memory usage: 22.4 MB

In [8]:
list_col = df.columns.to_list()

In [9]:
list_col.remove('hospital_death')

In [7]:
import statsmodels.api as sm

In [8]:
y = df['hospital_death']
x = df.drop('hospital_death', axis=1)

In [9]:
log_reg = sm.Logit(y, x).fit()

Optimization terminated successfully.
         Current function value: 0.224959
         Iterations 7

In [16]:
summary = log_reg.summary()

In [20]:
summary = summary.tables[1]

In [28]:
summary